CREATE TABLE SAVED_LOCATION (
	LOCATION_ID BLOB PRIMARY KEY,
	LOCATION_NAME TEXT,
	LOCATION_WORLD TEXT,
	LOCATION_OWNER BLOB,
	POS_X REAL,
	POS_Y REAL,
	POS_Z REAL
);

CREATE TABLE LOCATION_WHITELIST (
	LOCATION_ID BLOB,
	PLAYER_ID BLOB,
	PRIMARY KEY (LOCATION_ID,PLAYER_ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES SAVED_LOCATION(LOCATION_ID)
);
