api: '1.21.4'
api-version: 1.21.4
name: WorldIndex
version: 1.0.0
main: 'com.colbyreinhart.worldindex.WorldIndex'
description: 'Colby''s epic paper plugin'
author: 'Colby Reinhart'
website: 'https://colbyreinhart.com'
libraries:
  - org.xerial:sqlite-jdbc:3.49.1.0
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.0
commands:
  go:
    description: 'Access, use, and contribute to the community teleport list'
    usage: >
      Usage:
      /go to <location>
        Go to the specified location.
      /go list
        List all available locations to go to.
      /go add <name>
        Add a new location to the index.
      /go remove <name>
        Remove a location from the index. You may only remove locations that you own.
      /go help
        Display this message.
    permission: ''
